### TensorFlowの実行例

In [1]:
import tensorflow as tf

In [2]:
b: tf.Tensor = tf.constant(50)
b

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [4]:
matrix: tf.Tensor = tf.constant([[1, 2, 3,], [4, 5, 6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
x = b * 10
y = x + b
# Tensorflow v1.Xの書き方
with tf.Session() as sess:
    result = y.eval()
    print(result)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [19]:
x = b * 10
y:tf.Tensor = x + b
print(y)
print(f"numpy(): {y.numpy()}")
print(f"int(): {int(y)}")

tf.Tensor(550, shape=(), dtype=int32)
numpy(): 550
int(): 550
